set(NDEBUG_FLAGS "-DNDEBUG")
set(OPT_FLAGS="-march=native -mtune=native")

if (CMAKE_COMPILER_IS_GNUCXX)
    set(DEBUG_FLAGS "-ggdb3 -Og")
endif()

if(NOT DEFINED DEBUG_FLAGS)
    set(DEBUG_FLAGS "-g -O0")
endif()

set(CMAKE_BUILD_TYPE_INIT "DEBUG")

set(CMAKE_CXX_FLAGS_INIT "-Wall" )
set(CMAKE_C_FLAGS_INIT "-Wall")

set(CMAKE_CXX_FLAGS_DEBUG_INIT ${DEBUG_FLAGS})
set(CMAKE_C_FLAGS_DEBUG_INIT ${DEBUG_FLAGS})

set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT "-O2 ${OPT_FLAGS} ${DEBUG_FLAGS}")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT "-O2 ${OPT_FLAGS} ${DEBUG_FLAGS}")

set(CMAKE_CXX_FLAGS_RELEASE_INIT "-O3 ${OPT_FLAGS} ${NDEBUG_FLAGS}")
set(CMAKE_C_FLAGS_RELEASE_INIT "-O3 ${OPT_FLAGS} ${NDEBUG_FLAGS}")

set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT "-Os ${OPT_FLAGS} ${NDEBUG_FLAGS}")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT "-Os ${OPT_FLAGS} ${NDEBUG_FLAGS}")
